_target_: sparse_generalization.models.mlp.BasicMLPLit
_partial_: true

input_dim: 25
out_dim: 1 
hidden_dims: [32, 40]
embedding_inp: false
model_dim: 32
inp_size: 5 

lr: 5e-4
wd: 0.0

module:
  _partial_: true
  _target_: sparse_generalization.models.cnn.BasicCNN