_target_: sparse_generalization.models.cond_spartan.ConditionalSPARTAN
_partial_: true

inp_dim: 25
out_dim: 1 
layernorm: false
model_dim: 32
embedding_inp: false
num_heads: 1
num_mha_layers: 1
include_agg_layer: true
agg_residual: true
agg_res_coeff: 0.1
num_modes: 3
context_dim: 32
temp: 1.0
num_layers_film: 2
film_mlp: true
include_sparsity: false
lr: 1e-3
alpha: 0.1
residual: true
num_embeddings: 25
pe: true
val_freq: 5
num_eval_samples: 5
div_coeff: 0.0
use_optimal_test: true
sinusoidal: true
dropout: 0.0
device: cpu
beta1: 0.95
beta2: 0.999

div_loss: 
  _partial_: true
  _target_: sparse_generalization.layers.diversity_losses.CosineRepDiv
