_target_: sparse_generalization.models.hypernet.HyperNetSpartan
_partial_: true

inp_dim: 25
out_dim: 1 
layernorm: true
model_dim: 16
seq_len: 25
embedding_inp: false
num_heads: 1
hyper_type: qk
num_mha_layers: 1
num_agg_layers: 0
separate_mask: false
use_mask: false
flow_params:
  n_flows: 3
  hidden_features: [256, 256]
prior_params:
  n_flows: 3
  hidden_features: [128, 128]
prior_type: uniform
include_sparsity: false
lr: 1e-3
force_vae_gaussian: false
alpha: 0.25
residual: true
num_embeddings: 25
pe: true
beta: 1
sinusoidal: true
dropout: 0.0
device: cuda
beta1: 0.95
beta2: 0.999

prior_func: 
  _partial_: true
  _target_: sparse_generalization.layers.priors.make_unit_gaussian
  k: 10