_target_: sparse_generalization.models.hypernet.HyperNetSpartan
_partial_: true

inp_dim: 25
out_dim: 1 
layernorm: true
model_dim: 16
seq_len: 25
embedding_inp: false
num_heads: 1
hyper_type: qk
num_mha_layers: 1
include_agg_layer: true
forward_evals: 2
separate_mask: false
use_mask: false
flow_params:
  n_flows: 3
  hidden_features: [64, 64]
prior_params:
  n_flows: 3
  hidden_features: [32, 32]
prior_type: normal
include_sparsity: false
lr: 1e-3
force_vae_gaussian: false
alpha: 0.1
residual: true
num_embeddings: 25
pe_type: sin  # sin | coord | learned
beta: 1.0
val_freq: 5
num_eval_samples: 5
div_coeff: 1.0
use_optimal_test: true
dropout: 0.0
beta1: 0.9
beta2: 0.999
train_query: false

prior_func: 
  _partial_: true
  _target_: sparse_generalization.layers.priors.make_unit_gaussian
  k: 10

div_loss: 
  _partial_: true
  _target_: sparse_generalization.layers.diversity_losses.CosineRepDiv

