_target_: sparse_generalization.models.mlp.MLPBaseline
_partial_: true

inp_dim: 25
seq_len: 25
hidden_dims: [128, 128]
dropout: 0.0
input_method: concat  # concat | mean | max 
pe: false
inp_size: 5
embedding_inp: false
num_embeddings: 25
model_dim: 16
lr: 1e-3
wd: 0.0
beta1: 0.9
beta2: 0.999
val_freq: 5
use_optimal_test: false

# swap in the CNN with:
# module:
#   _partial_: true
#   _target_: sparse_generalization.models.cnn.BasicCNN
