_target_: sparse_generalization.models.spartan.OracleTransformer
_partial_: true

embed_size: 3
out_dim: 1
hidden_dims_ffn: [64, 64]
model_dim: 14
num_feature_layers: 1
num_heads: 1
residual: true
num_layers: 1
device: cpu