_target_: sparse_generalization.models.oracle.OracleTransformer
_partial_: true

embed_size: 3
out_dim: 2  
loss_type: ce  # ce | bce
hidden_dims_ffn: [64, 64]
model_dim: 14
num_feature_layers: 1
num_heads: 1
residual: true
num_layers: 1
lr_decay: linear  # none | linear
lr_warmup: false
