_target_: sparse_generalization.models.spartan.SPARTAN
_partial_: true

inp_dim: 25
out_dim: 1 
layernorm: true
agg_pool: false
model_dim: 32
embedding_inp: true
num_feature_layers: 3
num_heads: 1
num_layers: 1
include_sparsity: false
lr: 5e-4
token_pool: false
alpha: 0.1
residual: true
mask_res: false
zeros: false
pe: true
sinusoidal: true
path_sparsity: true
lagrangian: false
start_lambda: 1e15
target_loss: 0.115
cma: 0.9
step_size: 5e-1
dropout: 0.00
device: cuda
alpha_res: false
separate_mask: false
beta1: 0.9
beta2: 0.999

