_target_: sparse_generalization.models.spartan.SPARTAN
_partial_: true

inp_dim: 25
out_dim: 1 
hidden_dims_ffn: [128, 128]
layernorm: true
agg_pool: false
model_dim: 30
embedding_inp: false
num_feature_layers: 3
num_heads: 1
num_layers: 1
include_sparsity: false
lr: 5e-4
l1_weight: 1e-3
residual: true
pe: true
sinusoidal: false
path_sparsity: true
lagrangian: false
start_lambda: 1e15
target_loss: 0.115
cma: 0.9
step_size: 5e-1
dropout: 0.00
device: cuda
alpha_res: false
separate_mask: false
beta1: 0.9
beta2: 0.999

