_target_: sparse_generalization.models.transformer.TransformerLit
_partial_: true

inp_dim: 25
out_dim: 1 
layernorm: true
embedding_inp: false
agg_pool: false
model_dim: 30
num_feature_layers: 3
num_layers: 1
num_heads: 1
include_sparsity: false
l1_weight: 0.0001
positional_encoding: true
sinusoidal: false
lr: 5e-4
lagrangian: false
start_lambda: 5e6
target_loss: 0.15
cma: 0.9
step_size: 1e-1
noisy_grads: false
eta: 1.0
gamma: 0.55
noisy_bern: false
beta1: 0.9
beta2: 0.999
foopt: false
residual: True
hidden_dims: [128, 128]
dropout: 0.0

mha_layer:
  _partial_: true
  _target_: sparse_generalization.layers.thresh_mha.MultiHeadAttentionThresh
  threshold: 0.0


sparse_loss: 
  _partial_: true
  _target_: sparse_generalization.losses.sparse_loss.EntropyLoss