import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import RegularPolygon, Circle, Rectangle, Polygon, Ellipse, Wedge

from abc import abstractmethod

class Shape:

    def __init__(self, x, y, size=0.35, color='white'):
        self.x = x
        self.y = y
        self.size = size
        self.color = color

    @abstractmethod
    def draw(self, ax):
        ...

# from caroline's script
class Square(Shape):

    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-self.size, self.y-self.size), 
                         2*self.size, 2*self.size, color=self.color))
    
class CircleS(Shape):

    def draw(self, ax):
        ax.add_patch(Circle((self.x, self.y), self.size, color=self.color))
    
class Triangle(Shape):

    def draw(self, ax):
        ax.add_patch(RegularPolygon((self.x,self.y), 3, radius=self.size, color=self.color))
    
class Diamond(Shape):

    def draw(self, ax):
        verts = [(self.x,self.y+self.size),(self.x+self.size,self.y),(self.x,self.y-self.size),(self.x-self.size,self.y)]
        ax.add_patch(Polygon(verts, color=self.color))
    
class Pentagon(Shape):

    def draw(self, ax):
        ax.add_patch(RegularPolygon((self.x,self.y),5,radius=self.size,color=self.color))
    
class Heart(Shape):

    def draw(self, ax):
        t = np.linspace(0,2*np.pi,100)
        hx = self.size*16*np.sin(t)**3
        hy = self.size*(13*np.cos(t)-5*np.cos(2*t)-2*np.cos(3*t)-np.cos(4*t))
        hx = hx/18 + self.x
        hy = hy/18 + self.y
        ax.add_patch(Polygon(np.column_stack([hx,hy]), color=self.color))
    
class Star(Shape):

    def draw(self, ax):
        pts=[]
        for i in range(10):
            angle=i*np.pi/5
            r=self.size if i%2==0 else self.size*0.4
            pts.append((self.x+r*np.cos(angle), self.y+r*np.sin(angle)))
        ax.add_patch(Polygon(pts,color=self.color))
    
class Moon(Shape):

    def draw(self, ax):
        moon = Circle((self.x,self.y), self.size, color=self.color)
        ax.add_patch(moon)
        cover = Circle((self.x+self.size*0.4,self.y+self.size*0.1), self.size, color="white")
        ax.add_patch(cover)

class Plus(Shape):

    def draw(self, ax):
        t = self.size*0.6
        ax.add_patch(Rectangle((self.x-t/2,self.y-self.size), t,2*self.size, color=self.color))
        ax.add_patch(Rectangle((self.x-self.size,self.y-t/2), 2*self.size,t, color=self.color))

# --------------- NOTE: generated by gemini ----------------

class Hexagon(Shape):
    def draw(self, ax): ax.add_patch(RegularPolygon((self.x, self.y), 6, radius=self.size, color=self.color))

class Heptagon(Shape):
    def draw(self, ax): ax.add_patch(RegularPolygon((self.x, self.y), 7, radius=self.size, color=self.color))

class Octagon(Shape):
    def draw(self, ax): ax.add_patch(RegularPolygon((self.x, self.y), 8, radius=self.size, color=self.color))

class Nonagon(Shape):
    def draw(self, ax): ax.add_patch(RegularPolygon((self.x, self.y), 9, radius=self.size, color=self.color))

class Decagon(Shape):
    def draw(self, ax): ax.add_patch(RegularPolygon((self.x, self.y), 10, radius=self.size, color=self.color))

class Dodecagon(Shape):
    def draw(self, ax): ax.add_patch(RegularPolygon((self.x, self.y), 12, radius=self.size, color=self.color))

class SemiCircle(Shape):
    def draw(self, ax): ax.add_patch(Wedge((self.x, self.y), self.size, 0, 180, color=self.color))

class QuarterCircle(Shape):
    def draw(self, ax): ax.add_patch(Wedge((self.x, self.y), self.size, 0, 90, color=self.color))

class Capsule(Shape):
    def draw(self, ax): ax.add_patch(Ellipse((self.x, self.y), self.size*2, self.size, color=self.color))

class Ring(Shape):
    def draw(self, ax): ax.add_patch(Circle((self.x, self.y), self.size, color=self.color, fill=False, linewidth=5))

class Trapezoid(Shape):
    def draw(self, ax):
        v = [(self.x-self.size, self.y-self.size), (self.x+self.size, self.y-self.size), (self.x+0.6*self.size, self.y+self.size), (self.x-0.6*self.size, self.y+self.size)]
        ax.add_patch(Polygon(v, color=self.color))

class Parallelogram(Shape):
    def draw(self, ax):
        v = [(self.x-self.size, self.y-self.size), (self.x+0.5*self.size, self.y-self.size), (self.x+self.size, self.y+self.size), (self.x-0.5*self.size, self.y+self.size)]
        ax.add_patch(Polygon(v, color=self.color))

class CrossS(Shape):
    def draw(self, ax):
        for ang in [45, 135]:
            r = Rectangle((self.x-self.size, self.y-self.size*0.2), 2*self.size, self.size*0.4, color=self.color, angle=ang, rotation_point='center')
            ax.add_patch(r)

class EllipseV(Shape):
    def draw(self, ax): ax.add_patch(Ellipse((self.x, self.y), self.size, self.size*1.8, color=self.color))

class EllipseH(Shape):
    def draw(self, ax): ax.add_patch(Ellipse((self.x, self.y), self.size*1.8, self.size, color=self.color))

class Kite(Shape):
    def draw(self, ax):
        v = [(self.x, self.y+self.size), (self.x+0.6*self.size, self.y), (self.x, self.y-self.size*1.2), (self.x-0.6*self.size, self.y)]
        ax.add_patch(Polygon(v, color=self.color))

# --- 26-40: Nature & Weather ---
class Cloud(Shape):
    def draw(self, ax):
        for dx, dy, r in [(-0.5,0,0.5), (0.5,0,0.5), (0,0.3,0.6), (-0.2,-0.2,0.4), (0.2,-0.2,0.4)]:
            ax.add_patch(Circle((self.x+dx*self.size, self.y+dy*self.size), r*self.size, color=self.color))

class Leaf(Shape):
    def draw(self, ax):
        t = np.linspace(0, np.pi, 50)
        x = np.concatenate([np.sin(t), -np.sin(t)[::-1]]) * self.size + self.x
        y = np.concatenate([np.cos(t), np.cos(t)[::-1]]) * self.size + self.y
        ax.add_patch(Polygon(np.column_stack([x, y]), color=self.color))

class Flower(Shape):
    def draw(self, ax):
        for a in range(0, 360, 60):
            r = np.radians(a)
            ax.add_patch(Circle((self.x+np.cos(r)*self.size*0.6, self.y+np.sin(r)*self.size*0.6), self.size*0.4, color=self.color))
        ax.add_patch(Circle((self.x, self.y), self.size*0.2, color="gold"))

class Droplet(Shape):
    def draw(self, ax):
        ax.add_patch(Wedge((self.x, self.y-self.size*0.3), self.size*0.7, 180, 360, color=self.color))
        v = [(self.x-0.7*self.size, self.y-0.3*self.size), (self.x+0.7*self.size, self.y-0.3*self.size), (self.x, self.y+self.size)]
        ax.add_patch(Polygon(v, color=self.color))

class Bolt(Shape):
    def draw(self, ax):
        v = [(self.x-0.3*self.size, self.y+self.size), (self.x+0.4*self.size, self.y+0.1*self.size), (self.x-0.1*self.size, self.y+0.1*self.size), (self.x+0.3*self.size, self.y-self.size)]
        ax.add_patch(Polygon(v, color=self.color))

class Sun(Shape):
    def draw(self, ax):
        ax.add_patch(Circle((self.x, self.y), self.size*0.6, color=self.color))
        for i in range(8):
            ax.add_patch(RegularPolygon((self.x, self.y), 3, radius=self.size, color=self.color, orientation=i*np.pi/4))

class Tree(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-0.2*self.size, self.y-self.size), 0.4*self.size, self.size, color="brown"))
        ax.add_patch(RegularPolygon((self.x, self.y+0.2*self.size), 3, radius=self.size, color=self.color))

class PineTree(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-0.1*self.size, self.y-self.size), 0.2*self.size, 0.5*self.size, color="brown"))
        for i in range(3):
            ax.add_patch(RegularPolygon((self.x, self.y-0.2*self.size+i*0.5*self.size), 3, radius=0.7*self.size, color=self.color))

class Mushroom(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-0.3*self.size, self.y-self.size), 0.6*self.size, self.size, color="bisque"))
        ax.add_patch(Wedge((self.x, self.y-0.2*self.size), self.size, 0, 180, color=self.color))

class Crescent(Shape):
    def draw(self, ax):
        ax.add_patch(Circle((self.x, self.y), self.size, color=self.color))
        ax.add_patch(Circle((self.x + self.size*0.5, self.y), self.size*0.9, color="white"))

class Seed(Shape):
    def draw(self, ax): ax.add_patch(Ellipse((self.x, self.y), self.size*0.6, self.size, angle=45, color=self.color))

class Mountain(Shape):
    def draw(self, ax):
        ax.add_patch(Polygon([(self.x-self.size, self.y-self.size), (self.x+self.size, self.y-self.size), (self.x, self.y+self.size)], color=self.color))
        ax.add_patch(Polygon([(self.x-0.3*self.size, self.y+0.4*self.size), (self.x+0.3*self.size, self.y+0.4*self.size), (self.x, self.y+self.size)], color="white"))

class Wave(Shape):
    def draw(self, ax):
        t = np.linspace(0, 2*np.pi, 50)
        x = np.linspace(-self.size, self.size, 50) + self.x
        y = 0.3*self.size*np.sin(t*2) + self.y
        ax.plot(x, y, color=self.color, linewidth=3)

class Egg(Shape):
    def draw(self, ax): ax.add_patch(Ellipse((self.x, self.y), self.size*1.2, self.size*1.6, color=self.color))

class Apple(Shape):
    def draw(self, ax):
        ax.add_patch(Circle((self.x-0.3*self.size, self.y), 0.7*self.size, color=self.color))
        ax.add_patch(Circle((self.x+0.3*self.size, self.y), 0.7*self.size, color=self.color))
        ax.add_patch(Rectangle((self.x-0.05*self.size, self.y+0.5*self.size), 0.1*self.size, 0.5*self.size, color="brown"))

# --- 41-55: Common Objects ---
class House(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-self.size, self.y-self.size), 2*self.size, 1.2*self.size, color=self.color))
        ax.add_patch(Polygon([(self.x-self.size, self.y+0.2*self.size), (self.x+self.size, self.y+0.2*self.size), (self.x, self.y+self.size)], color=self.color))

class Envelope(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-self.size, self.y-0.7*self.size), 2*self.size, 1.4*self.size, color=self.color, fill=False, linewidth=2))
        ax.add_patch(Polygon([(self.x-self.size, self.y+0.7*self.size), (self.x+self.size, self.y+0.7*self.size), (self.x, self.y)], color=self.color, alpha=0.5))

class ArrowUp(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-0.2*self.size, self.y-self.size), 0.4*self.size, self.size, color=self.color))
        ax.add_patch(Polygon([(self.x-0.8*self.size, self.y), (self.x+0.8*self.size, self.y), (self.x, self.y+self.size)], color=self.color))

class ArrowDown(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-0.2*self.size, self.y), 0.4*self.size, self.size, color=self.color))
        ax.add_patch(Polygon([(self.x-0.8*self.size, self.y), (self.x+0.8*self.size, self.y), (self.x, self.y-self.size)], color=self.color))

class Shield(Shape):
    def draw(self, ax):
        v = [(self.x-self.size, self.y+self.size), (self.x+self.size, self.y+self.size), (self.x+self.size, self.y), (self.x, self.y-self.size), (self.x-self.size, self.y)]
        ax.add_patch(Polygon(v, color=self.color))

class Key(Shape):
    def draw(self, ax):
        ax.add_patch(Circle((self.x-0.5*self.size, self.y), 0.5*self.size, color=self.color, fill=False, linewidth=3))
        ax.add_patch(Rectangle((self.x, self.y-0.1*self.size), self.size, 0.2*self.size, color=self.color))
        ax.add_patch(Rectangle((self.x+0.7*self.size, self.y-0.4*self.size), 0.2*self.size, 0.4*self.size, color=self.color))

class Bell(Shape):
    def draw(self, ax):
        ax.add_patch(Wedge((self.x, self.y-0.4*self.size), self.size*0.8, 0, 180, color=self.color))
        ax.add_patch(Rectangle((self.x-0.8*self.size, self.y-0.6*self.size), 1.6*self.size, 0.2*self.size, color=self.color))
        ax.add_patch(Circle((self.x, self.y-0.8*self.size), 0.2*self.size, color=self.color))

class Gem(Shape):
    def draw(self, ax):
        v = [(self.x-0.5*self.size, self.y+self.size), (self.x+0.5*self.size, self.y+self.size), (self.x+self.size, self.y+0.4*self.size), (self.x, self.y-self.size), (self.x-self.size, self.y+0.4*self.size)]
        ax.add_patch(Polygon(v, color=self.color))

class Search(Shape):
    def draw(self, ax):
        ax.add_patch(Circle((self.x-0.2*self.size, self.y+0.2*self.size), 0.6*self.size, fill=False, edgecolor=self.color, linewidth=3))
        ax.add_patch(Rectangle((self.x+0.2*self.size, self.y-0.2*self.size), 0.8*self.size, 0.2*self.size, angle=-45, color=self.color))

class Flag(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-self.size, self.y-self.size), 0.1*self.size, 2*self.size, color="black"))
        ax.add_patch(Polygon([(self.x-0.9*self.size, self.y+self.size), (self.x+self.size, self.y+0.5*self.size), (self.x-0.9*self.size, self.y)], color=self.color))

class Tag(Shape):
    def draw(self, ax):
        v = [(self.x-self.size, self.y+0.5*self.size), (self.x+0.4*self.size, self.y+0.5*self.size), (self.x+self.size, self.y), (self.x+0.4*self.size, self.y-0.5*self.size), (self.x-self.size, self.y-0.5*self.size)]
        ax.add_patch(Polygon(v, color=self.color))

class Gear(Shape):
    def draw(self, ax):
        ax.add_patch(Circle((self.x, self.y), 0.7*self.size, color=self.color))
        for i in range(8):
            ax.add_patch(Rectangle((self.x-0.1*self.size, self.y+0.7*self.size), 0.2*self.size, 0.3*self.size, color=self.color, angle=i*45, rotation_point='center'))
        ax.add_patch(Circle((self.x, self.y), 0.3*self.size, color="white"))

class Bottle(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-0.5*self.size, self.y-self.size), self.size, 1.4*self.size, color=self.color))
        ax.add_patch(Rectangle((self.x-0.2*self.size, self.y+0.4*self.size), 0.4*self.size, 0.6*self.size, color=self.color))

class Cup(Shape):
    def draw(self, ax):
        v = [(self.x-0.7*self.size, self.y-self.size), (self.x+0.7*self.size, self.y-self.size), (self.x+self.size, self.y+self.size), (self.x-self.size, self.y+self.size)]
        ax.add_patch(Polygon(v, color=self.color))

class Phone(Shape):
    def draw(self, ax):
        ax.add_patch(Rectangle((self.x-0.6*self.size, self.y-self.size), 1.2*self.size, 2*self.size, color=self.color, lw=2))
        ax.add_patch(Circle((self.x, self.y-0.8*self.size), 0.1*self.size, color=self.color))

# --- 56-64: Star Variants ---
class Star3(Shape):
    def draw(self, ax):
        pts = []
        for i in range(6):
            a = i * np.pi / 3
            r = self.size if i % 2 == 0 else self.size * 0.3
            pts.append((self.x + r * np.cos(a), self.y + r * np.sin(a)))
        ax.add_patch(Polygon(pts, color=self.color))

class Star4(Shape):
    def draw(self, ax):
        pts = []
        for i in range(8):
            a = i * np.pi / 4
            r = self.size if i % 2 == 0 else self.size * 0.3
            pts.append((self.x + r * np.cos(a), self.y + r * np.sin(a)))
        ax.add_patch(Polygon(pts, color=self.color))

class Star6(Shape):
    def draw(self, ax):
        pts = []
        for i in range(12):
            a = i * np.pi / 6
            r = self.size if i % 2 == 0 else self.size * 0.5
            pts.append((self.x + r * np.cos(a), self.y + r * np.sin(a)))
        ax.add_patch(Polygon(pts, color=self.color))

class Star8(Shape):
    def draw(self, ax):
        pts = []
        for i in range(16):
            a = i * np.pi / 8
            r = self.size if i % 2 == 0 else self.size * 0.5
            pts.append((self.x + r * np.cos(a), self.y + r * np.sin(a)))
        ax.add_patch(Polygon(pts, color=self.color))

class Burst(Shape):
    def draw(self, ax):
        pts = []
        for i in range(30):
            a = i * np.pi / 15
            r = self.size if i % 2 == 0 else self.size * 0.7
            pts.append((self.x + r * np.cos(a), self.y + r * np.sin(a)))
        ax.add_patch(Polygon(pts, color=self.color))

class Asterisk(Shape):
    def draw(self, ax):
        for i in range(6):
            ax.add_patch(Rectangle((self.x-self.size, self.y-0.1*self.size), 2*self.size, 0.2*self.size, color=self.color, angle=i*30, rotation_point='center'))

class Snowflake(Shape):
    def draw(self, ax):
        for i in range(6):
            ang = i * 60
            ax.add_patch(Rectangle((self.x-self.size, self.y-0.05*self.size), 2*self.size, 0.1*self.size, color=self.color, angle=ang, rotation_point='center'))
            r_x = self.x + 0.7*self.size*np.cos(np.radians(ang))
            r_y = self.y + 0.7*self.size*np.sin(np.radians(ang))
            ax.add_patch(RegularPolygon((r_x, r_y), 6, radius=0.2*self.size, color=self.color))

class Clover(Shape):
    def draw(self, ax):
        for a in [0, 90, 180, 270]:
            r = np.radians(a)
            ax.add_patch(Circle((self.x+np.cos(r)*0.5*self.size, self.y+np.sin(r)*0.5*self.size), 0.5*self.size, color=self.color))

class DiamondRing(Shape):
    def draw(self, ax):
        ax.add_patch(Circle((self.x, self.y-0.2*self.size), 0.7*self.size, fill=False, edgecolor=self.color, lw=3))
        v = [(self.x, self.y+self.size), (self.x+0.3*self.size, self.y+0.6*self.size), (self.x, self.y+0.2*self.size), (self.x-0.3*self.size, self.y+0.6*self.size)]
        ax.add_patch(Polygon(v, color=self.color))


SHAPE_MAP = {
    "square": Square, 
    "circle": CircleS, 
    "triangle": Triangle, 
    "diamond": Diamond, 
    "pentagon": Pentagon,
    "heart": Heart, 
    "star": Star, 
    "moon": Moon, 
    "plus": Plus, 
    "hexagon": Hexagon, 
    "heptagon": Heptagon,
    "octagon": Octagon, 
    "nonagon": Nonagon, 
    "decagon": Decagon, 
    "dodecagon": Dodecagon, 
    "semicircle": SemiCircle,
    "quartercircle": QuarterCircle, 
    "capsule": Capsule, 
    "ring": Ring, 
    "trapezoid": Trapezoid, 
    "parallelogram": Parallelogram,
    "cross": CrossS, 
    "ellipse_v": EllipseV, 
    "ellipse_h": EllipseH, 
    "kite": Kite, 
    "cloud": Cloud, 
    "leaf": Leaf,
    "flower": Flower, 
    "droplet": Droplet, 
    "bolt": Bolt, 
    "sun": Sun, 
    "tree": Tree, 
    "pinetree": PineTree,
    "mushroom": Mushroom, 
    "crescent": Crescent, 
    "seed": Seed, 
    "mountain": Mountain, 
    "wave": Wave, 
    "egg": Egg,
    "apple": Apple, 
    "house": House, 
    "envelope": Envelope, 
    "arrow_up": ArrowUp, 
    "arrow_down": ArrowDown,
    "shield": Shield, 
    "key": Key, 
    "bell": Bell, 
    "gem": Gem, 
    "search": Search, 
    "flag": Flag, 
    "tag": Tag,
    "gear": Gear, 
    "bottle": Bottle, 
    "cup": Cup, 
    "phone": Phone, 
    "star3": Star3, 
    "star4": Star4, 
    "star6": Star6,
    "star8": Star8, 
    "burst": Burst, 
    "asterisk": Asterisk, 
    "snowflake": Snowflake, 
    "clover": Clover, 
    "diamondring": DiamondRing
}